### ISSUE TITLE
Killing Java Process on Remote Device

### ISSUE THREAD

**Issue by asebak** [asebak/raspberrypi-intellij#30]
Currently when deployment occurs it does "kill all java".  This is bad as it will kill all java process on remote target.  What needs to be done is to only kill the pid thats occupying the port.  (need to find the proper linux command to this).

**Comment by tloehr** [comment]
Hi m8.

This works fine (just tested it).

``` bash
kill $(lsof -i|grep 58053|awk '{print $2}')
```

In this example 58053 is the listening port.

**Comment by asebak** [comment]
Yeah but this is for debugging, but what about if you are running it because when you run it, it's not listening to any port?

**Comment by tloehr** [comment]
So You are looking for a filter (for debug and normal mode) which securely returns the right process id to kill ?

**Comment by asebak** [comment]
yes exactly and that it will kill that PID at the same time,  but didn't know how to do this!

**Comment by asebak** [comment]
this is what I got so far:
kill -9 $(`ps -efww | grep "projectPath"| grep -v grep | tr -s " "| cut -d" " -f2)
