### ISSUE TITLE
Maybe not to re-deploy all the jars every time to reduce deploy time

### ISSUE THREAD

**Issue by Z-Clive** [asebak/raspberrypi-intellij#42]
Great job man! It's really handy for guys like us who want to deploy and remote debug on raspberry pi.

I've noticed that there's a directory called `lib` in each project which contains many jars I assume will be needed for debugging. However, the jars tend to be re-deployed every time you click debug in intellij. And because some of the jars are really big like `rt.jar`, it'll extremely slow down the deploy session.

So I'm suggesting maybe not to deploy those jars every time, make it a one time thing when each project was first deployed on raspberry. Or maybe even consider make it share among all the projects. If there's new jars needed, copy it, but if the jar it needed is already been deployed, just use the one.

Thanks for the effort, I really appreciate it. ;-)

**Comment by asebak** [comment]
@zmLGBBM Thanks for the kind words :+1:.  I will definitely check into it.
