### ISSUE TITLE
Raspi always shuts down after one debug run

### ISSUE THREAD

**Issue by tloehr** [asebak/raspberrypi-intellij#44]
As soon as I finish the debug run with my application, the raspi shuts down immediately.

**Comment by asebak** [comment]
really? your whole raspbery pi just shuts down completely? I never had this issue.  Any more info you want to provide?

**Comment by tloehr** [comment]
Yes. The debugging ends (runs as sudo) and then it shuts down. Have to turn it off and on again.

## 

Mit freundlichen Grüßen,
Torsten Löhr

Am 7. August 2015 bei 14:16:23, Ahmad Sebak (notifications@github.com) schrieb:

really? your whole raspbery pi just shuts down completely?

**Comment by asebak** [comment]
@tloehr I am on vacation now so I don't got my equipment here, so I won't be able to look into this issue until i get back :S

**Comment by tloehr** [comment]
No worries. Thanks for caring. Enjoy Your vacation. We will talk, when You return home.

Ciao for now.

---

sent from my iPhone

**Comment by tloehr** [comment]
Sorry. This has nothing to do with your plugin. Will try to close it.
Thanks Dude...

**Comment by asebak** [comment]
@tloehr what did this have to do with?

**Comment by tloehr** [comment]
Well. It was an embarrassing cockup for me. ;-)

Apparently when You try to address a 16x2 LCD display on the same pins where you already installed a pitft driver for, and none of both is connected then the following line will NOT simply return -1, no, it will shutdown the raspi immediately. 

```
    // initialize LCD
    // the wiring is according to the examples from https://kofler.info/buecher/raspberry-pi/
    // LCD data bit 8 (set to 0 if using 4 bit communication)
    lcdHandle = Lcd.lcdInit(LCD_ROWS,     // number of row supported by LCD
            LCD_COLUMNS,  // number of columns supported by LCD
            LCD_BITS,     // number of bits used to communicate to LCD
            11,           // LCD RS pin
            10,           // LCD strobe pin
            6,            // LCD data bit 1
            5,            // LCD data bit 2
            4,            // LCD data bit 3
            1,            // LCD data bit 4
            0,            // LCD data bit 5 (set to 0 if using 4 bit communication)
            0,            // LCD data bit 6 (set to 0 if using 4 bit communication)
            0,            // LCD data bit 7 (set to 0 if using 4 bit communication)
            0);
```

Back in university the first rule when something went wrong was always "never blame the compiler". Didn't follow that rule this time. Sorry for the inconvenience.
