### ISSUE TITLE
Cannot connect to the Embedded System Target Unable to reach a settlement:

### ISSUE THREAD

**Issue by ghost** [asebak/raspberrypi-intellij#45]
Hello,

after I upgrade my Raspberry Pi to the new Rasbian OS (jessy)
I get this error message:

Deploying to the Embedded Target
bash
Cannot connect to the Embedded System Target Unable to reach a settlement: [diffie-hellman-group1-sha1] and [curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha1]

What does that mean?

Thank you
Marc-Kevin

![screenshot](https://cloud.githubusercontent.com/assets/11948791/10345753/0e4142f2-6d2c-11e5-8b91-294398a8bd99.jpg)

**Comment by asebak** [comment]
give me a couple of weeks since I am out of town and don't got my hardware boards to debug this issue.

**Comment by asebak** [comment]
@mkb81 still working on this issue, much more complex than I anticipated!

**Comment by ZynThaX** [comment]
Having the same problem, is there anything I can help you with. 
Maby some testning that needs to be done or some problem you're stuck on that I can help with?

**Comment by asebak** [comment]
@ZynThaX Yeah if you can fix it that would be great, problem is with the library I am using SSHJ, seems like with the latest OS it does not work great with it!

**Comment by ghost** [comment]
Is there anything I can help you too?

**Comment by asebak** [comment]
@mkb81 give me another week I have been busy with other things. If it's not completed by then I will come back to you.
