### ISSUE TITLE
Cannot connect to Raspberry Pi

### ISSUE THREAD

**Issue by cjm27** [asebak/raspberrypi-intellij#46]
I tried this plugin hoping to make programming and debugging the Raspberry Pi easier, but I cannot get it to work. When I click the validate connection button, it shows cannot connect to remote target. And running it will invoke this error:
`Cannot connect to the Embedded System Target Unable to reach a settlement: [diffie-hellman-group1-sha1] and [curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group14-sha1]`
I cannot find the problem. The hostname is the same as the IP address used for SSH, and I tried various ports.

Any help will be greatly appreciated. Thanks!

**Comment by asebak** [comment]
@cjm27 It was already reported, it was an operating system problem.  I am already taking a look at it.

**Comment by cjm27** [comment]
@asebak Sorry about the duplication. Thanks for clarifying it.
