### ISSUE TITLE
Debug Raspberry Pi Error gragent.jar -> Gradle Support

### ISSUE THREAD

**Issue by jalucenyo** [asebak/raspberrypi-intellij#57]
Hello 

I got an error while trying to run debug on a Mac OSX against a raspberry pi plate.
I get the following message appears.

Thanks

```
Executing Command :sudo kill -9 $(ps -efww | grep "com.jalcdeveloper.testrpi.Main"| grep -v grep | tr -s " "| cut -d" " -f2)
Executing Command :cd /home/pi/IdeaProjects/TestRpi01
Executing Command :tar -xvf TestRpi01.tar
Executing Command :rm *.tar
Executing Command :sudo java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5555 -javaagent:/Users/jalucenyo/Library/Caches/IntelliJIdea15/groovyHotSwap/gragent.jar -cp classes:lib/'*' com.jalcdeveloper.testrpi.Main
classes/com/jalcdeveloper/testrpi/Main.class

Error opening zip file or JAR manifest missing : /Users/jalucenyo/Library/Caches/IntelliJIdea15/groovyHotSwap/gragent.jar

Error occurred during initialization of VM
agent library failed to init: instrument

Process finished with exit code 1
```

**Comment by asebak** [comment]
Interesting I never tested it on MAC OSX, are you sure this is a plugin issue?  It's hard for me to debug this, can you send me your project if you would like to share it?

**Comment by Akkell** [comment]
Got the same issue on Windows 10.
Look at the line

```
Executing Command :sudo java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5555 -javaagent:/Users/jalucenyo/Library/Caches/IntelliJIdea15/groovyHotSwap/gragent.jar -cp classes:lib/'*' com.jalcdeveloper.testrpi.Main
classes/com/jalcdeveloper/testrpi/Main.class
```

I suspect that the plugin supplies wrong path in `javaagent` argument. This is the path to `gragent.jar` on _developer PC_, but  should be the path on the _embedded device_. 

May be the issue is Gradle-related? Does the plugin support Gradle?

**Comment by Akkell** [comment]
Just tested on the new clean project (without Gradle) - debug works.

Line in question doesn't contain `javaagent` argument:
`Executing Command :sudo java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5555 -cp classes:lib/'*' com.company.App`

Seems like Gradle projects aren't supported. Please implement Gradle projects support.

**Comment by asebak** [comment]
@Akkell thanks for figuring that out, I will look into it. I never tested gradle, only maven based projects.

**Comment by AledLewis** [comment]
I've submitted a fix for the issue 
https://github.com/asebak/embeddedlinux-jvmdebugger-intellij/pull/63

**Comment by asebak** [comment]
should be avaible in next release.
