### ISSUE TITLE
Old command lines, <=java 1.8

### ISSUE THREAD

**Issue by kkuez** [asebak/raspberrypi-intellij#80]
There are still written the old debug arguments in the code, in 1.8 syntax was changed to `-agentlib:jdwp=transport=dt_socket,server=y,address=*:12345`

May be a quick fix.

**Comment by matthiasklein** [comment]
I have the same problem. Remote debugging is not possible with Java 11.

I would love to see a fixed version of the plugin.

**Comment by kkuez** [comment]
> I have the same problem. Remote debugging is not possible with Java 11.
> 
> I would love to see a fixed version of the plugin.

Found a solution for this, using intellij:

On rpi 

> sudo java -client -agentlib:jdwp=transport=dt_socket,server=y,address=*:12345 -jar Path_To_Program.jar

(In my case a .jar)

In Intellij, u can configurate "Remote" as run:
(Sorry I dont know how to insert pictures here, so...:)
https://www.imagebanana.com/s/big/1489/FJdQXKur.png

I hope it'll help you @matthiasklein 

VG!

Intellij 18.3
OpenJdk11

**Comment by asebak** [comment]
fixed thanks @oliversaggau
