### ISSUE TITLE
Connection Refused on Debugging

### ISSUE THREAD

**Issue by fortuneNext** [asebak/raspberrypi-intellij#82]
My raspberry pi 3b+ (fresh rasbian, latest version) is perfectly reachable within the network via SSH or pings.
With the Embedded Linux JVM Debugger, I can succesfully deploy my software project and run it on the raspberry.
Anyhow, when I try to debug the program, im getting an error:

"Error running 'Embedded Device Debugger (1234)':
Unable to open debugger port (raspberrypi4:1234 java.net.ConnectException "Connection refused: connect""

The last message from the log is
Listening for transport dt_socket at address: 1234

![Unbenannt](https://user-images.githubusercontent.com/33626569/68071243-e87e3980-fd78-11e9-9baa-838093d73841.PNG)

which I can't really understand. On my last raspberry (using NOOBS) it perfectly worked out of the box. What could be wrong?

Btw: The Plugin is great, I would love to see it further developed (e.g. beeing able to insert environment variables for DISPLAY and stuff)! Great work! :)

**Comment by okosiuta** [comment]
same problem with raspberry pi 4

**Comment by kevingre** [comment]
I think this is due to JDK 11.  I can run this plugin fine on JDK 8 but it does indeed give this error if attempting to debug on JDK11.
